name: pappyism
favicon: null
layout_spectrum: 0.9333579072263092
typography_spectrum: 0.3451430567074567
title: 'Pappyism: providing you with parenting advice without all the preaching. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9769688800442964
  lightness: 0.07221823092550039
  saturation: 0.6668849929701537
  rhythmicContrast: 0.73778619710356
purpose: []
